services:
  # ==========================================
  # 🚀 Mpesa Connect SERVICES
  # ==========================================
  mpesaconnect-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - PORT=5454
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5454:5454"
    networks:
      - app_net

  mpesaconnect-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=https://mpesaconnect.co.ke/api
      - PORT=5054
    depends_on:
      - mpesaconnect-api
    ports:
      - "5054:5054"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
