#!/bin/bash

echo "=========================================="
echo "   Fixing Prisma Migration Lock"
echo "=========================================="

cd /var/www/mpesaconnect.co.ke/backend

echo "🔧 Updating migration lock to MySQL..."
cat > prisma/migrations/migration_lock.toml << EOF
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "mysql"
EOF

echo ""
echo "🗄️  Creating CRM migration..."
npx prisma migrate deploy

echo ""
echo "✅ Migration lock fixed!"
echo ""
echo "Now rebuilding backend..."
cd ..
./update.sh
