import crypto from 'crypto';
import path from 'path';
import fs from 'fs';

/**
 * Safaricom Daraja Sandbox Public Key (2048-bit RSA)
 *
 * Official Safaricom Daraja Sandbox Public Key used for encrypting the
 * Initiator Password into a SecurityCredential for Daraja Sandbox API calls.
 */
export const DARAJA_SANDBOX_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqLcFdVcV7HdEOotsNLoM
PhD74CX1ejzcgfNuiJNy9pTySxbszBBCWxmok3Unul4rX/zyVD/6LDb9nbqRywZI
gR46UOn+tR3vGXXPX6igxgS6DYTaQV8W858yOGLuhowRi5xeQJfczAMU4o+sCxlB
bMCqYs4nzW81fi8iF2OEUdrfJcbamhSnksdgfD/nomWy9MESAz1QufrGBnaRX2N0
CKsi8SNmzsghpfP15VLiIVV8YXPFKtd9sY37FpY28OKGjKG5wdije/bzFL8qEcPD
hqYGuVaGkhX1bkI0iH+UcFtYYrZv/Fyb5jRHXmNLiq4mMG0fMH8ENxNACFtRZTDI
IQIDAQAB
-----END PUBLIC KEY-----`;

/**
 * Check if a given string is already a pre-computed SecurityCredential.
 * Safaricom SecurityCredentials generated by Safaricom portal or RSA encryption
 * are Base64 strings of 172 chars (1024-bit) or 344 chars (2048-bit).
 */
export const isPrecomputedSecurityCredential = (value?: string | null): boolean => {
    if (!value || typeof value !== 'string') return false;
    const clean = value.trim().replace(/\s+/g, '');
    // Base64 regex and length >= 160 characters
    return clean.length >= 160 && /^[A-Za-z0-9+/=]+$/.test(clean);
};

/**
 * Clean and format certificate / public key string into valid PEM.
 */
const formatAsPem = (certStr: string): string => {
    const trimmed = certStr.trim();
    if (trimmed.includes('BEGIN CERTIFICATE') || trimmed.includes('BEGIN PUBLIC KEY')) {
        return trimmed;
    }
    return `-----BEGIN CERTIFICATE-----\n${trimmed}\n-----END CERTIFICATE-----`;
};

/**
 * Generate a Daraja SecurityCredential by RSA-encrypting the initiator password.
 *
 * If the input is already a pre-computed SecurityCredential (pasted from Safaricom Developer Portal),
 * it is returned directly without re-encrypting.
 *
 * @param passwordOrCredential - Initiator Password or pre-computed SecurityCredential
 * @param isProduction - Whether to use production (true) or sandbox (false) environment
 * @param customCert - Optional custom X.509 certificate or public key string (PEM format)
 * @returns Base64-encoded encrypted SecurityCredential for Daraja API
 */
export const generateSecurityCredential = (
    passwordOrCredential: string,
    isProduction: boolean = false,
    customCert?: string | null
): string => {
    const raw = (passwordOrCredential || '').trim();
    if (!raw) {
        throw new Error(
            'Initiator Password or Security Credential is required. Configure it in Settings → M-Pesa → Initiator Information.'
        );
    }

    // 1. If user passed an already pre-computed SecurityCredential, return it cleaned
    if (isPrecomputedSecurityCredential(raw)) {
        const cleaned = raw.replace(/\s+/g, '');
        console.log(`[Daraja Security] Using pre-computed SecurityCredential (length: ${cleaned.length})`);
        return cleaned;
    }

    // 2. Resolve Public Certificate / Key
    let keyOrCert: string | null = null;

    // Check custom cert passed directly from profile
    if (customCert && customCert.trim().length > 100) {
        try {
            const pem = formatAsPem(customCert);
            crypto.createPublicKey(pem);
            keyOrCert = pem;
            console.log('[Daraja Security] Using verified custom certificate provided in settings');
        } catch (e: any) {
            console.warn('[Daraja Security] Provided custom certificate failed parse:', e.message);
        }
    }

    // Check MPESA_CERT_PATH env variable
    if (!keyOrCert && process.env.MPESA_CERT_PATH) {
        try {
            const certPath = path.resolve(process.env.MPESA_CERT_PATH);
            const fileContent = fs.readFileSync(certPath, 'utf8');
            if (fileContent && fileContent.length > 100) {
                const pem = formatAsPem(fileContent);
                crypto.createPublicKey(pem);
                keyOrCert = pem;
                console.log(`[Daraja Security] Using certificate from file: ${certPath}`);
            }
        } catch (err: any) {
            console.warn(`[Daraja Security] Could not load MPESA_CERT_PATH (${process.env.MPESA_CERT_PATH}): ${err.message}`);
        }
    }

    // Check bundled certificate files in src/certs/
    if (!keyOrCert) {
        const certFileName = isProduction ? 'production.cer' : 'sandbox.cer';
        const bundledPath = path.join(__dirname, '..', 'certs', certFileName);
        try {
            if (fs.existsSync(bundledPath)) {
                const fileContent = fs.readFileSync(bundledPath, 'utf8');
                if (fileContent && fileContent.length > 300) {
                    const pem = formatAsPem(fileContent);
                    crypto.createPublicKey(pem);
                    keyOrCert = pem;
                    console.log(`[Daraja Security] Using valid bundled certificate: ${certFileName}`);
                }
            }
        } catch {
            // Bundled file wasn't valid, continue
        }
    }

    // Embedded Sandbox Key fallback
    if (!keyOrCert && !isProduction) {
        keyOrCert = DARAJA_SANDBOX_PUBLIC_KEY;
        console.log('[Daraja Security] Using embedded Daraja Sandbox Public Key');
    }

    // If in Production and no valid certificate found
    if (!keyOrCert) {
        throw new Error(
            'Production Daraja certificate is required to encrypt your Initiator Password. ' +
            'Either: 1) Generate a Security Credential on the Safaricom Developer Portal (https://developer.safaricom.co.ke/test_credentials) ' +
            'and paste it into Settings → M-Pesa → Security Credential, or 2) Paste your Production Certificate PEM into Settings.'
        );
    }

    try {
        const encrypted = crypto.publicEncrypt(
            {
                key: keyOrCert,
                padding: crypto.constants.RSA_PKCS1_PADDING,
            },
            Buffer.from(raw, 'utf8')
        );

        const result = encrypted.toString('base64');
        console.log(`[Daraja Security] SecurityCredential successfully generated (length: ${result.length})`);
        return result;
    } catch (err: any) {
        console.error('[Daraja Security] RSA encryption failed:', err.message);
        throw new Error(
            `Failed to encrypt Initiator Password: ${err.message}. ` +
            'Please generate a pre-computed Security Credential from the Safaricom Developer Portal and paste it into Settings → M-Pesa.'
        );
    }
};

/**
 * Determine if production or sandbox based on env string
 */
export const isProductionEnv = (env?: string | null): boolean => {
    const normalized = (env || '').trim().toLowerCase();
    return normalized === 'production' || normalized === 'live';
};

